extend type AnemiaAssessment {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "AnemiaAssessment", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `AnemiaAssessment`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID @fdc_generated(from: "AnemiaAssessment.user", purpose: IMPLICIT_REF_FIELD)
}
extend type DietaryIntake {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "DietaryIntake", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `DietaryIntake`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID @fdc_generated(from: "DietaryIntake.user", purpose: IMPLICIT_REF_FIELD)
}
extend type HealthMetric {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "HealthMetric", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `HealthMetric`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID @fdc_generated(from: "HealthMetric.user", purpose: IMPLICIT_REF_FIELD)
}
extend type SymptomEntry {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "SymptomEntry", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `SymptomEntry`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID @fdc_generated(from: "SymptomEntry.user", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
